api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
     # Default value
    collection:
            pagination:
                items_per_page_parameter_name: itemsPerPage # Default value
                client_items_per_page: true # Disabled by default
                enabled: true
                page_parameter_name: page
                client_enabled: true
    swagger:
         api_keys:
             apiKey:
                name: Authorization
                type: header


    # The list of enabled error formats. The first one will be the default.
   