api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
     # Default value

    swagger:
         api_keys:
             apiKey:
                name: Authorization
                type: header


    # The list of enabled error formats. The first one will be the default.
   